from sqlalchemy import Column, Integer, String, Text, ForeignKey, DateTime, func
from sqlalchemy.orm import relationship
from app.database import Base

'''
    Job post model
    stores the job posts 
'''
class Job(Base):
    __tablename__ = "jobs"

    id = Column(Integer, primary_key=True, index=True)
    job_title = Column(String(150), nullable=False)
    location = Column(String(100), nullable=False)
    work_type = Column(String(50), nullable=False)
    generated_description = Column(Text, nullable=False)  # this will store the description generated by ai

    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())



    user = relationship("User", back_populates="jobs") 
    cvs = relationship("CV", back_populates="job")
    applications = relationship("Application", back_populates="job")

